version: '3'
services:
  oracle-xe:
    build: .
    container_name: oracle-xe
    ports:
      - "${DB_PORT}:1521"
      - "${EM_PORT}:5500"
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
      - INIT_SGA_SIZE=${INIT_SGA_SIZE}
      - INIT_PGA_SIZE=${INIT_PGA_SIZE}
      - ORACLE_ENABLE_XDB=true  
    volumes:
      - ./scripts:/container-entrypoint-initdb.d
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Changez le mot de passe pour plus de sécurité
    networks:
      - monitoring

  oracle-exporter:
    image: iamseth/oracledb_exporter:latest
    container_name: oracle-exporter
    environment:
      - DATA_SOURCE_NAME=${DB_USER}/${DB_PASSWORD}@oracle-xe:1521/XE
    ports:
      - "9161:9161"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
