-- 01_create_tables.sql
CREATE USER my_user IDENTIFIED BY monAppMotDePasse;
GRANT CONNECT, RESOURCE TO my_user;


CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(50),
  position VARCHAR2(50),
  salary NUMBER,
  PRIMARY KEY (employee_id)
);
